# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_day', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dailymenu',
                'ordering': ('availability_day',),
            },
        ),
        migrations.CreateModel(
            name='MenuAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailymenus.DailyMenu')),
            ],
        ),
    ]
